# -*- coding: utf-8 -*-
"""Linear Regression Project-

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TkA27rfnmLbYG08f0LnoSpqx8Yu7TFFH
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#%matplotlib inline: the output of plotting commands is displayed inline within frontends like the Jupyter notebook, directly below the code cell that produced it. 
# %matplotlib inline

import os
print(os.listdir("/content"))

data = pd.read_csv("/content/Ecommerce Customers.csv")

data.head()

data.describe()

data.info()

sns.jointplot(x="Time on Website", y="Yearly Amount Spent", data = data)

"""# **EDA STARTS**"""

sns.jointplot(data = data, x="Time on App", y="Yearly Amount Spent")

sns.jointplot(data=data, x="Time on App", y="Length of Membership", kind="hex")

sns.pairplot(data)

# We can see here that Length of Membership is the most correlated feature with Yearly Amount Spent 
# So, Creating a linear model plot (using seaborn's lmplot) of Yearly Amount Spent vs. Length of Membership.

sns.set(color_codes=True)
sns.lmplot(data=data, x="Length of Membership", y="Yearly Amount Spent")

X = data[['Avg. Session Length', 'Time on App', 'Time on Website', 'Length of Membership']]
Y = data['Yearly Amount Spent']

"""# **TRAINING AND TESTING STARTS**"""

print(X.shape, Y.shape)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 101)
lm = LinearRegression()

lm.fit(X_train, Y_train)
print(lm.coef_)

predictions = lm.predict(X_test)

plt.scatter(Y_test, predictions)
plt.ylabel("Predictions")
plt.xlabel("Y Test")

import sklearn.metrics as metrics
print('Mean Absolute Error: {}'.format(metrics.mean_absolute_error(Y_test, predictions)))
print('Mean Square Error: {}'.format(metrics.mean_squared_error(Y_test, predictions)))
print('Root Mean Square Error: {}'.format(np.sqrt(metrics.mean_squared_error(Y_test, predictions))))

# Residuals
sns.distplot((Y_test-predictions))

pd.DataFrame(lm.coef_ , X.columns, columns=['Coeffecient'])

# Hence Time on APP is the most correlated feature and the company should focus on the APP more!!!